### ISSUE TITLE
HEIC file to png가 이루어지지 않는 것 같아서 해결방안을 가져왔습니다.

### ISSUE THREAD

**Issue by devUuung** [Hitbee-dev/converts_image#1]
Image.open()은 Window에서만 그런건진 모르겠으나 HEIC 파일이 열 수 없게 되어있습니다. 그래서 pillow_heif 라이브러리를 사용해 약식으로 코드를 짜보았습니다.

```
from PIL import Image
import pillow_heif

heif_file = pillow_heif.read_heif("./images/IMG_7950.HEIC")
image = Image.frombytes(
  heif_file.mode,
  heif_file.size,
  heif_file.data,
  "raw",
)

image.save("./IMG_7950.png", format("png"))
```

**Comment by Hitbee-dev** [comment]
> 

와 블펭님 이게 얼마만인가요.. 잘 지내고 계시죠?
감사합니다.
M1 MacOS만 사용중이어서 pillow_heif 라이브러리를 사용할 수 없어 고민중에 있었습니다...ㅋㅋㅋ

도움주심에 감사합니다.

**Comment by Hitbee-dev** [comment]
> Image.open()은 Window에서만 그런건진 모르겠으나 HEIC 파일이 열 수 없게 되어있습니다. 그래서 pillow_heif 라이브러리를 사용해 약식으로 코드를 짜보았습니다.
> 
> ```
> from PIL import Image
> import pillow_heif
> 
> heif_file = pillow_heif.read_heif("./images/IMG_7950.HEIC")
> image = Image.frombytes(
>   heif_file.mode,
>   heif_file.size,
>   heif_file.data,
>   "raw",
> )
> 
> image.save("./IMG_7950.png", format("png"))
> ```

와 블펭님 이게 얼마만인가요.. 잘 지내고 계시죠?
감사합니다.
M1 MacOS만 사용중이어서 pillow_heif 라이브러리를 사용할 수 없어 고민중에 있었습니다...ㅋㅋㅋ

도움주심에 감사합니다.

**Comment by Hitbee-dev** [comment]
https://github.com/python-pillow/Pillow/issues/5093

ISSUE에 등록되어있는 내용 중 이 내용으로 시간 될 때 테스트 한번 해봐야겠네요.

![image](https://user-images.githubusercontent.com/83276163/179900432-610679f5-4a76-460e-aa07-e41b06ea2cd0.png)

**Comment by Hitbee-dev** [comment]
+ PYPI 공식 홈페이지에 이런 내용도 있군요.
구현 후 Cloud Service까지 연동해 보겠습니다 : )

![image](https://user-images.githubusercontent.com/83276163/179900608-4c718729-a4cb-44a1-b944-074f43206575.png)

**Comment by Hitbee-dev** [comment]
@blpeng2 Fork하신 Repo를 보니 이미 구현 하셨군요..!
괜찮으시면 Pull Request 보내주세요!

**Comment by blpeng2** [comment]
@Hitbee-dev 금방 보내드리겠습니다!
